apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: argocd
  labels:
    ram: muzaffarpur
  
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    


